name: macOS

on:
  push:
    paths:
      - '**'
      - '!README.md'
      - '!.gitignore'
      - '!ubuntu/**'
      - '!.github/workflows/**'
      - '.github/workflows/macos.yml'

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - run: zsh macos/init.sh
      - run: zsh macos/install.sh
      - run: zsh macos/defaults.sh
      - run: zsh vscode/init.sh
      - run: zsh vscode/install.sh
      - run: zsh iterm2/init.sh
