name: macOS

on:
  push:
    paths:
      - '**'
      - '!README.md'
      - '!.gitignore'
      - '!ubuntu/**'

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - run: bash init.sh
      - run: bash macos/init.sh
      - run: bash macos/install.sh
      - run: bash iterm2/init.sh
      - run: bash vscode/init.sh
      - run: bash vscode/install.sh
      - run: bash macos/defaults.sh
