name: Ubuntu

on:
  push:
    paths:
      - '**'
      - '!README.md'
      - '!.gitignore'
      - '!macos/**'
      - '!.github/workflows/**'
      - '.github/workflows/ubuntu.yml'

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: bash ubuntu/init.sh
      - run: bash ubuntu/install.sh
      - run: bash vscode/init.sh
      - run: bash vscode/install.sh
